version: '1.0.{build}'
image: Visual Studio 2017
#branches:
#  only:
#    - develop
#    - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./Linq2ShadowTests/Linq2ShadowTests.csproj --verbosity m
build_script:
  - cmd: dotnet build ./Linq2Shadow/Linq2Shadow.csproj -c Release
test_script:
  - cmd: dotnet restore ./Linq2ShadowTests/Linq2ShadowTests.csproj --verbosity m
  - cmd: dotnet test -c Release -v minimal
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
artifacts:
  - path: .\**\*.nupkg
    name: NuGet
deploy:
  - provider: Environment
    name: Nuget
    artifact: '*.nupkg'
    skip_symbols: false
    on:
      branch: master
  - provider: Environment
    name: GitHub
    artifact: '*.nupkg'
    skip_symbols: false
    on:
      branch: master  